title: Indoor Activity Recognition with mmWave Radar Sensor
email: wm@mengw.io
description: Indoor Activity Recognition with mmWave Radar Sensor
url: https://something
github_username: SmartHomeLab
theme: minima
repository: SmartHomeLab/something
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
author:
  name: SmartHomeLab
  email: wm@mengw.io
plugins:
  - jekyll-github-metadata
exclude:
  - .jekyll-cache/
  - docs/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - makefile
