title: something
email: wm@mengw.io
description: Indoor Activity Recognition with mmWave Radar Sensor
url: https://something
github_username: SmartHomeLab
remote_theme: pages-themes/midnight@v0.2.0
repository: SmartHomeLab/something
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
author:
  name: SmartHomeLab
  email: wm@mengw.io
plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
exclude:
  - .jekyll-cache/
  - docs/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
